FROM nginx:alpine

ARG branch

RUN mkdir -p /config-buildtime/log/

# copy everything
COPY ./ /config-buildtime/

# remove default nginx config
RUN rm -R /etc/nginx/*

# copy start script
COPY start.sh start.prod.sh /

# make start script executable
RUN chmod +x /start.sh

EXPOSE 80

ENTRYPOINT ["sh","/start.prod.sh",${branch}]
