FROM nginx:alpine

RUN apk add npm git

RUN mkdir -p /config-buildtime/log/

# copy everything
COPY ./ .gitignore .gitlab-ci.yml /config-buildtime/
COPY .git/ /config-buildtime/.git/

# remove default nginx config
RUN rm -R /etc/nginx/*

# copy start script
COPY start.sh start.dev.sh /

# make start script executable
RUN chmod +x /start.sh

EXPOSE 80

ENTRYPOINT ["sh","/start.dev.sh"]
